<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="imu" params="parent">

        <joint name="imu_joint" type="fixed">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}_link"/>
            <child link="imu_frame"/>
        </joint>

        <link name="imu_frame">

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.02 0.02 ${layer_h/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.02 0.02 ${layer_h/2}"/>
                </geometry>
            </collision>

        </link>

    </xacro:macro>

</robot>