<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="lidar" params="parent">

        <xacro:property name="lidar_joint_origin">
            <origin xyz="0 0 ${lidar_height/2 + 0.072}" rpy="0.0 0.0 0.0"/>
        </xacro:property>

        <joint name="lidar_joint" type="fixed">
            <xacro:insert_block name="lidar_joint_origin"/>
            <parent link="${parent}_link"/>
            <child link="lidar_frame"/>
        </joint>

        <link name="lidar_frame">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder  mass="${lidar_mass}" radius="${lidar_radius}" length="${lidar_height}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

    </xacro:macro>

</robot>
