<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="wheel" params="name parent mass radius thickness side_FB side_LR">

        <link name="${name}_wheel_link">

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
                <material name="yellow">
                    <color rgba="${255/255} ${237/255} ${40/255} 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder  mass="${mass}" radius="${radius}" length="${thickness}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
  
        </link>

        <gazebo reference="${name}_wheel_link">
			<mu1 value="0.5"/>
			<mu2 value="0.5"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

        <joint name="${name}_wheel_joint" type="continuous">

            <parent link="${parent}_link"/>

            <child link="${name}_wheel_link"/>

            <origin xyz="${wheel_offset_fb*side_FB} ${wheel_offset_lr*side_LR} -${wheel_offset_z}" rpy="${-side_LR*PI/2} 0.0 0.0"/>

            <axis xyz="0 0 ${side_LR}" rpy="0 0 0" />

        </joint>

        <!-- <transmission name="${name}_wheel_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_wheel_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission> -->

        <gazebo reference="${name}_wheel_link">
            <material>Gazebo/Yellow</material>       
        </gazebo>

    </xacro:macro>

</robot>
