<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="mecanum_wheel" params="name parent mass radius thickness side_FB side_LR">

        <xacro:property name="wheel_joint_origin">
            <origin xyz="${wheel_offset_fb*side_FB} ${wheel_offset_lr*side_LR} -${wheel_offset_z}" rpy="-${PI/2} 0.0 0.0"/>
        </xacro:property>

        <link name="${name}_wheel_link">
            <visual>
                <xacro:if value="${side_FB == 1}">
                    <origin xyz="0.0 0.0 0.0" rpy="${PI} 0.0 0.0"/>
                    <geometry>
                        <xacro:if value="${side_LR == 1}">
                            <mesh filename="package://mecabot_body/meshes/mecanum_wheel_2.stl" scale="0.001 0.001 0.001"/>
                        </xacro:if>
                        <xacro:if value="${side_LR == -1}">
                            <mesh filename="package://mecabot_body/meshes/mecanum_wheel_1.stl" scale="0.001 0.001 0.001"/>
                        </xacro:if>
                    </geometry>
                </xacro:if>
                <xacro:if value="${side_FB == -1}">
                    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <xacro:if value="${side_LR == 1}">
                            <mesh filename="package://mecabot_body/meshes/mecanum_wheel_1.stl" scale="0.001 0.001 0.001"/>
                        </xacro:if>
                        <xacro:if value="${side_LR == -1}">
                            <mesh filename="package://mecabot_body/meshes/mecanum_wheel_2.stl" scale="0.001 0.001 0.001"/>
                        </xacro:if>
                    </geometry>
                </xacro:if>
                <material name="yellow">
                    <color rgba="${255/255} ${237/255} ${40/255} 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder  mass="${mass}" radius="${radius}" length="${thickness}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
  
        </link>

        <joint name="${name}_wheel_joint" type="continuous">

            <parent link="${parent}_link"/>

            <child link="${name}_wheel_link"/>

            <xacro:insert_block name="wheel_joint_origin" />

            <axis xyz="0 0 1" rpy="0 0 0" />

            <dynamic damping="0.01" friction="0.0"/>

        </joint>

        <gazebo reference="${name}_wheel_link">
            <material>Gazebo/Grey</material>
            <mu1>0.0</mu1>
            <mu2>0.0</mu2>
            <TurnGravityOff>false</TurnGravityOff>
        </gazebo>

    </xacro:macro>

</robot>
