<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="use_simulation" default="false"/>

    <xacro:include filename="$(find mecabot_description)/urdf/include/common_macros.xacro"/>
    <xacro:include filename="$(find mecabot_description)/urdf/include/materials.xacro"/>

    <xacro:include filename="$(find mecabot_description)/urdf/chassis/layer.xacro"/>
    <xacro:include filename="$(find mecabot_description)/urdf/wheels/wheel.xacro"/>
    <xacro:include filename="$(find mecabot_description)/urdf/wheels/mecanum_wheel.xacro"/>

    <xacro:include filename="$(find mecabot_description)/urdf/sensors/imu.xacro"/>
    <xacro:include filename="$(find mecabot_description)/urdf/sensors/lidar.xacro"/>

    <!--~~~~~~~~~~ BASE LINK ~~~~~~~~~~-->
    <link name="base_link">
    </link>

    <!--~~~~~~~~~~ CHASSIS LAYERS ~~~~~~~~~~-->
    <xacro:layer name="lower_layer" parent="base" mass="${layer_mass}" 
                length="${layer_l}" width="${layer_w-wheel_thickness*2}" height="${layer_h}" reflect="0"/>

    <xacro:layer name="upper_layer" parent="base" mass="${layer_mass}" 
                length="${layer_l}" width="${layer_w-wheel_thickness*2}" height="${layer_h}" reflect="1"/>

    <!--~~~~~~~~~~ MECANUM WHEEL LINKS ~~~~~~~~~~-->
    <xacro:wheel name="front_left" parent="base" mass="${wheel_mass}" 
                radius="${wheel_radius}" thickness="${wheel_thickness}" side_FB="1" side_LR="1"/> 
    <xacro:wheel name="front_right" parent="base" mass="${wheel_mass}" 
                radius="${wheel_radius}" thickness="${wheel_thickness}" side_FB="1" side_LR="-1"/>
    <xacro:wheel name="back_left" parent="base" mass="${wheel_mass}" 
                radius="${wheel_radius}" thickness="${wheel_thickness}" side_FB="-1" side_LR="1"/>
    <xacro:wheel name="back_right" parent="base" mass="${wheel_mass}" 
                radius="${wheel_radius}" thickness="${wheel_thickness}" side_FB="-1" side_LR="-1"/>

    <!--~~~~~~~~~~ LIDAR ~~~~~~~~~~-->
    <xacro:lidar parent="upper_layer"/> 
    <!--~~~~~~~~~~ IMU ~~~~~~~~~~-->
    <xacro:imu parent="upper_layer"/>

    <!--~~~~~~~~~~ Extra simulation components (if use Gazebo). Change condition to False when run on real robot  ~~~~~~~~~~-->
    <xacro:if value="$(arg use_simulation)">
        <!-- Publish joints' state -->
        <gazebo>
            <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
                <jointName>front_left_wheel_joint, front_right_wheel_joint, back_left_wheel_joint, back_right_wheel_joint</jointName>
            </plugin>
        </gazebo>

        <!-- Lidar simulation using Gazebo. -->
        <gazebo reference="lidar_frame">
            <material>Gazebo/Black</material>
            <sensor name="laser" type="ray">
                <pose> 0 0 0 0 0 0 </pose>
                <visualize>true</visualize>
                <update_rate>30</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>359</samples>
                            <resolution>1</resolution>
                            <min_angle>-3.14</min_angle>
                            <max_angle>3.14</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.2</min>
                        <max>12</max>
                        <resolution>0.01</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.02</stddev>
                    </noise>
                </ray>
                <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
                    <robotNamespace>/</robotNamespace>
                    <topicName>/scan</topicName>
                    <frameName>lidar_frame</frameName>
                </plugin>
            </sensor>
        </gazebo>

        <!-- IMU simulation using Gazebo. -->
        <gazebo reference="imu_frame">
            <gravity>true</gravity>
            <sensor name="imu_sensor" type="imu">
                <always_on>true</always_on>
                <update_rate>100</update_rate>
                <visualize>true</visualize>
                <topic>__default_topic__</topic>
                <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                    <robotNamespace>/</robotNamespace>
                    <topicName>/imu</topicName>
                    <bodyName>imu_frame</bodyName>
                    <updateRateHZ>10.0</updateRateHZ>
                    <gaussianNoise>0.0</gaussianNoise>
                    <xyzOffset>0 0 0</xyzOffset>
                    <rpyOffset>0 0 0</rpyOffset>
                    <frameName>imu_frame</frameName>
                    <initialOrientationAsReference>false</initialOrientationAsReference>
                </plugin>
                <pose>0 0 0 0 0 0</pose>
            </sensor>
        </gazebo>
    </xacro:if>

</robot>