<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="imu" params="parent">

        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${parent}_link"/>
            <child link="imu_frame"/>
        </joint>

        <link name="imu_frame">

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.02 0.02 ${layer_h/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.02 0.02 ${layer_h/2}"/>
                </geometry>
            </collision>

        </link>

        <gazebo reference="imu_frame">
            <gravity>true</gravity>
            <sensor name="imu_sensor" type="imu">
                <always_on>true</always_on>
                <update_rate>100</update_rate>
                <visualize>true</visualize>
                <topic>__default_topic__</topic>
                <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                    <topicName>imu</topicName>
                    <bodyName>imu_frame</bodyName>
                    <updateRateHZ>10.0</updateRateHZ>
                    <gaussianNoise>0.0</gaussianNoise>
                    <xyzOffset>0 0 0</xyzOffset>
                    <rpyOffset>0 0 0</rpyOffset>
                    <frameName>imu_frame</frameName>
                    <initialOrientationAsReference>false</initialOrientationAsReference>
                </plugin>
                <pose>0 0 0 0 0 0</pose>
            </sensor>
        </gazebo>

    </xacro:macro>

</robot>