map_update_interval: 2.5
maxUrange: 12.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 10
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 75
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.05
angularUpdate: 0.05
temporalUpdate: 1
resampleThreshold: 0.5
particles: 100
xmin: -20.0
ymin: -20.0
xmax: 20.0
ymax: 20.0
delta: 0.05
llsamplerange: 0.05
llsamplestep: 0.05
lasamplerange: 0.005
lasamplestep: 0.005
transform_publish_period: 0.5